version: '3.4'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - merzigo-network

  contentservice.api:
    image: ${DOCKER_REGISTRY-}contentapi
    build:
      context: .
      dockerfile: src/Merzigo.ContentService/Merzigo.ContentService.Api/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - merzigo-network

  userservice.api:
    image: ${DOCKER_REGISTRY-}userapi
    build:
      context: .
      dockerfile: src/Merzigo.UserService/Merzigo.UserService.Api/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - merzigo-network

volumes:
  postgres-db:

networks:
  merzigo-network: